### ISSUE TITLE
Error 500 vendiendo bono directo a usuario antiguo sin perfil

### ISSUE THREAD

**Issue by rasca** [fuegoaustral/ticketera#105]
Tenemos usuarios sin Perfil, o con perfil en blanco y tira este error:

```
[1730837415242] Zappa Event: {'resource': '/{proxy+}', 'path': '/admin/caja/email-has-account/', 'httpMethod': 'POST', 'headers': {'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept-Language': 'es-AR,es;q=0.8,en-US;q=0.5,en;q=0.3', 'CloudFront-Forwarded-Proto': 'https', 'CloudFront-Is-Desktop-Viewer': 'true', 'CloudFront-Is-Mobile-Viewer': 'false', 'CloudFront-Is-SmartTV-Viewer': 'false', 'CloudFront-Is-Tablet-Viewer': 'false', 'CloudFront-Viewer-ASN': '7303', 'CloudFront-Viewer-Country': 'AR', 'content-type': 'application/json', 'Cookie': '_ga=GA1.1.1287219191.1730799342; _ga_6VF2B93MG7=GS1.1.1730799341.1.0.1730799341.0.0.0; csrftoken=DW0tbXZrnrDvUrtXPegT5ezx4O0lJ2gm; cw_conversation=eyJhbGciOiJIUzI1NiJ9.eyJzb3VyY2VfaWQiOiJlNmVlNmZiMS03OGU3LTRhNDQtYTk4Ni05ZTIxMjgwMjg4ZWEiLCJpbmJveF9pZCI6NDY0Nzh9.V-2KYGKu5EZObzK05fnh0zo0ht86XUFbG8OESZjFLCQ; cw_user_raBFfLmbvescyg5Vdvui7enZ=a9f9378fae1e9137cce8ecf655254c25; sessionid=sg148rcisaqbzkqq4czyipq2hbyfjbud', 'dnt': '1', 'Host': 'eventos.fuegoaustral.org', 'origin': 'https://eventos.fuegoaustral.org', 'priority': 'u=0', 'Referer': 'https://eventos.fuegoaustral.org/admin/direct_tickets/', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'cors', 'sec-fetch-site': 'same-origin', 'sec-gpc': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0', 'Via': '2.0 3ef3b9a0bbfaafd94db8ed4837e0f90e.cloudfront.net (CloudFront)', 'X-Amz-Cf-Id': '3fg8-7iXG6edlGfpY1F6dgkXNd9jYZ7gkGX-LvfNI4XM_VBcDDJLHQ==', 'X-Amzn-Trace-Id': 'Root=1-672a7ba7-16ca809e0434d7c729f51c59', 'x-csrftoken': 'eGPydpNruFWnlHUoUb5RR4vZkeQDgZ9RHsFRecCIHWpI5YdbzfbAM8UmeSGOPRf3', 'X-Forwarded-For': '181.104.26.4, 130.176.220.172', 'X-Forwarded-Port': '443', 'X-Forwarded-Proto': 'https'}, 'multiValueHeaders': {'Accept': ['*/*'], 'Accept-Encoding': ['gzip, deflate, br, zstd'], 'Accept-Language': ['es-AR,es;q=0.8,en-US;q=0.5,en;q=0.3'], 'CloudFront-Forwarded-Proto': ['https'], 'CloudFront-Is-Desktop-Viewer': ['true'], 'CloudFront-Is-Mobile-Viewer': ['false'], 'CloudFront-Is-SmartTV-Viewer': ['false'], 'CloudFront-Is-Tablet-Viewer': ['false'], 'CloudFront-Viewer-ASN': ['7303'], 'CloudFront-Viewer-Country': ['AR'], 'content-type': ['application/json'], 'Cookie': ['_ga=GA1.1.1287219191.1730799342; _ga_6VF2B93MG7=GS1.1.1730799341.1.0.1730799341.0.0.0; csrftoken=DW0tbXZrnrDvUrtXPegT5ezx4O0lJ2gm; cw_conversation=eyJhbGciOiJIUzI1NiJ9.eyJzb3VyY2VfaWQiOiJlNmVlNmZiMS03OGU3LTRhNDQtYTk4Ni05ZTIxMjgwMjg4ZWEiLCJpbmJveF9pZCI6NDY0Nzh9.V-2KYGKu5EZObzK05fnh0zo0ht86XUFbG8OESZjFLCQ; cw_user_raBFfLmbvescyg5Vdvui7enZ=a9f9378fae1e9137cce8ecf655254c25; sessionid=sg148rcisaqbzkqq4czyipq2hbyfjbud'], 'dnt': ['1'], 'Host': ['eventos.fuegoaustral.org'], 'origin': ['https://eventos.fuegoaustral.org'], 'priority': ['u=0'], 'Referer': ['https://eventos.fuegoaustral.org/admin/direct_tickets/'], 'sec-fetch-dest': ['empty'], 'sec-fetch-mode': ['cors'], 'sec-fetch-site': ['same-origin'], 'sec-gpc': ['1'], 'User-Agent': ['Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0'], 'Via': ['2.0 3ef3b9a0bbfaafd94db8ed4837e0f90e.cloudfront.net (CloudFront)'], 'X-Amz-Cf-Id': ['3fg8-7iXG6edlGfpY1F6dgkXNd9jYZ7gkGX-LvfNI4XM_VBcDDJLHQ=='], 'X-Amzn-Trace-Id': ['Root=1-672a7ba7-16ca809e0434d7c729f51c59'], 'x-csrftoken': ['eGPydpNruFWnlHUoUb5RR4vZkeQDgZ9RHsFRecCIHWpI5YdbzfbAM8UmeSGOPRf3'], 'X-Forwarded-For': ['181.104.26.4, 130.176.220.172'], 'X-Forwarded-Port': ['443'], 'X-Forwarded-Proto': ['https']}, 'queryStringParameters': None, 'multiValueQueryStringParameters': None, 'pathParameters': {'proxy': 'admin/caja/email-has-account'}, 'stageVariables': None, 'requestContext': {'resourceId': 'ecexx1', 'resourcePath': '/{proxy+}', 'httpMethod': 'POST', 'extendedRequestId': 'AyhCMEQ3IAMEjxw=', 'requestTime': '05/Nov/2024:20:10:15 +0000', 'path': '/admin/caja/email-has-account/', 'accountId': '251799394474', 'protocol': 'HTTP/1.1', 'stage': 'prod', 'domainPrefix': 'eventos', 'requestTimeEpoch': 1730837415225, 'requestId': '5c9be31e-c47c-4982-abf7-59f8a3de0c28', 'identity': {'cognitoIdentityPoolId': None, 'accountId': None, 'cognitoIdentityId': None, 'caller': None, 'sourceIp': '181.104.26.4', 'principalOrgId': None, 'accessKey': None, 'cognitoAuthenticationType': None, 'cognitoAuthenticationProvider': None, 'userArn': None, 'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0', 'user': None}, 'domainName': 'eventos.fuegoaustral.org', 'deploymentId': 'se6266', 'apiId': '4ybi3aow7i'}, 'body': 'eyJlbWFpbCI6ImFsbWlyb25hbmFAZ21haWwuY29tIn0=', 'isBase64Encoded': True}
[1730837415242] host found: [eventos.fuegoaustral.org]
[1730837415293] Internal Server Error: /admin/caja/email-has-account/
[1730837415293] Traceback (most recent call last):
[1730837415293] File "/tmp/deprepagos/django/core/handlers/exception.py", line 55, in inner
[1730837415293] response = get_response(request)
[1730837415293] File "/tmp/deprepagos/django/core/handlers/base.py", line 197, in _get_response
[1730837415293] response = wrapped_callback(request, *callback_args, **callback_kwargs)
[1730837415293] File "/tmp/deprepagos/django/contrib/auth/decorators.py", line 23, in _wrapper_view
[1730837415293] return view_func(request, *args, **kwargs)
[1730837415293] File "/tmp/deprepagos/django/contrib/auth/decorators.py", line 23, in _wrapper_view
[1730837415293] return view_func(request, *args, **kwargs)
[1730837415293] File "/tmp/deprepagos/tickets/admin.py", line 39, in email_has_account
[1730837415293] if user.profile.profile_completion == 'COMPLETE':
[1730837415293] File "/tmp/deprepagos/django/db/models/fields/related_descriptors.py", line 492, in __get__
[1730837415293] raise self.RelatedObjectDoesNotExist(
[1730837415293] django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
[1730837415299] 181.104.26.4 - - [05/Nov/2024:20:10:15 +0000] "POST /admin/caja/email-has-account/ HTTP/1.1" 500 145 "https://eventos.fuegoaustral.org/admin/direct_tickets/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0" 0/56787.0
```

**Comment by rasca** [comment]
Y en esta línea no se les pide completar el perfil a los ususarios staff que son los mismos que tenían cuenta antes: https://github.com/fuegoaustral/ticketera/blob/dev/tickets/middleware.py#L12
